# Generated by Django 4.1.4 on 2022-12-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='landing',
        ),
    ]
