# Generated by Django 4.1.4 on 2022-12-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_member_landing'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField(max_length=50)),
                ('gender', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
