# Generated by Django 4.1.4 on 2022-12-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(max_length=50)),
                ('gender', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='landing',
        ),
        migrations.DeleteModel(
            name='personal',
        ),
    ]
